BEGIN;

CREATE TABLE IF NOT EXISTS "VERSION" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "VALUE" INTEGER,
    "FILE" TEXT,
    "CREATED_AT" TEXT DEFAULT CURRENT_TIMESTAMP,
    "DELETED" INT DEFAULT 0,
    "DELETED_AT" TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS unique_value_deleted 
ON VERSION(VALUE)
WHERE DELETED = 0;


COMMIT;