BEGIN;

CREATE TABLE IF NOT EXISTS "test" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT UNIQUE,
);

CREATE TABLE IF NOT EXISTS "VERSION" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "VERSION" INT UNIQUE,
    "FILE" TEXT,
    "CREATED_AT" TEXT,
)

COMMIT;