BEGIN;

CREATE TABLE IF NOT EXISTS "TEST" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT UNIQUE,
    "CREATED_AT" TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "VERSION" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "VALUE" INTEGER UNIQUE,
    "FILE" TEXT,
    "CREATED_AT" TEXT DEFAULT CURRENT_TIMESTAMP
);

COMMIT;