BEGIN;

CREATE TABLE IF NOT EXISTS "TEST2" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT UNIQUE,
    "CREATED_AT" TEXT DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "VERSION" ADD COLUMN "DELETED_AT" TEXT;

COMMIT;